{% set name = "sagemaker-studio-sparkmagic-lib" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sagemaker_studio_sparkmagic_lib-{{ version }}.tar.gz
  sha256: 6dac6e80f331b5587aac389f41625a83f825dfa5b913f185b83053e1d4c8a470

build:
  entry_points:
    - sm-sparkmagic=sagemaker_studio_sparkmagic_lib.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - boto3 >=1.10.44,<2.0
    - ipython

test:
  imports:
    - sagemaker_studio_sparkmagic_lib
  commands:
    - pip check
    - sm-sparkmagic --help
  requires:
    - pip

about:
  home: https://github.com/aws-samples/sagemaker-studio-sparkmagic-conf
  summary: Python Command line tool to manage configuration of sparkmagic kernels on studio
  license: MIT-0
  license_family: MIT
  license_file:
    - NOTICE
    - LICENSE.txt
    - LICENSE

extra:
  recipe-maintainers:
    - just4brown
